language: cpp
os: osx

env:
    matrix:
        - CONFIGURATION=Debug
        - CONFIGURATION=Release

install:
    - brew install qt5
    - export PATH=/usr/local/opt/qt5/bin:$PATH

before_script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$CONFIGURATION

script:
    - cmake --build .
    - ctest -V
    - qmlscene --quit -I ../qml ../examples/TestApp.qml
